[project]
name = "proxy-interceptor"
version = "0.1.0"
description = "A PyQt6 application for intercepting and displaying HTTP requests"
requires-python = ">=3.8"
dependencies = [
    "PyQt6>=6.5.0",
]

[project.scripts]
proxy-interceptor = "proxy_interceptor.main:main"
